<?xml version="1.0"?>
<package format="3">
  <name>low_speed_av_bringup</name>
  <version>0.1.0</version>
  <description>低速自动驾驶规划控制启动、配置和样例数据。</description>
  <maintainer email="demo@example.com">low_speed_av</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>low_speed_av_planning</exec_depend>
  <exec_depend>low_speed_av_control</exec_depend>
  <exec_depend>low_speed_av_simulation</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <test_depend>chassis_interfaces</test_depend>
  <test_depend>diagnostic_msgs</test_depend>
  <test_depend>geometry_msgs</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>
  <test_depend>low_speed_av_interfaces</test_depend>
  <test_depend>nav_msgs</test_depend>
  <test_depend>python3-pytest</test_depend>
  <test_depend>rclpy</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
